### PR TITLE
added new api versioning support

### PR DESCRIPTION
**Pull request by meza**
As [4sq changed their versioning scheme](https://developer.foursquare.com/overview/versioning), this modification should come in handy.

### CODE REVIEW

**Comment by rk295** [comment]
thx! Finding this pull request saved me some time this morning :)

**Comment by rk295** [comment]
Thanks for merging.

**Comment by meza** [comment]
:+1: finally I can delete my fork :D
Thx for the merge

**Comment by jmathai** [comment]
Thanks for the PR :). Sorry it took so long.

**Pull request merged**
